name: Maven CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build Car Service
        run: mvn -B -f carservice/pom.xml clean install -DskipTests

      - name: Build Reservation Service
        run: mvn -B -f reservation/pom.xml clean install -DskipTests

      - name: Build Cloud Gateway
        run: mvn -B -f cloud-gateway/pom.xml clean install -DskipTests

      - name: Build Service Registry
        run: mvn -B -f service-registry/pom.xml clean install -DskipTests

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: microservices-jars
          path: "**/target/*.jar"
